apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu 
spec:
  nodeSelector:
    gpu: "true"
  containers:
  -
    image: edmelkoyev/kubia
    imagePullPolicy: Always
    name: kubia
    ports:
    - 
      containerPort: 8080
      protocol: TCP
